services:
  backend:
    image: star_swapper-backend
    pull_policy: never
    container_name: star_swapper-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      #By specifying target: prod, Docker will only build up to the prod stage, skipping earlier stages (like build). This can save time and resources if you only need the final, production-ready image.
      target: prod
    ports:
    - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - app-network
  
  frontend:
    image: star_swapper-frontend
    pull_policy: never
    container_name: star_swapper-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
      args:
        VITE_BACKEND_URL: http://localhost:3000
    ports:
    -  "5173:5173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge